# Generated by Django 4.2.2 on 2023-11-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='card_images')),
            ],
        ),
    ]
